AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'PatronService'

Resources:
  OnSiteHoldRequestServiceService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handle_event
      Runtime: ruby2.7
      Timeout: 60
      Environment:
        Variables:
          LOG_LEVEL: debug
          SIERRA_API_BASE_URL: https://nypl-sierra-test.nypl.org/iii/sierra-api/v6/
          SIERRA_OAUTH_URL: https://nypl-sierra-test.nypl.org/iii/sierra-api/v6/token
          SIERRA_OAUTH_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHoweAYJKoZIhvcNAQcGoGswaQIBADBkBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDOcLof0wS+XIKrTc+QIBEIA3U0vf8ZaPKeyWsTF9VmuIThYmkQr1UYAvnbkSQVeXf90n+h/3JHk0WwoSPSVK9yG6/WxCzIJPkA==
          SIERRA_OAUTH_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGowaAYJKoZIhvcNAQcGoFswWQIBADBUBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDB20W+OqtkHEZQ7jvwIBEIAnZDf6KmlbYbOMmjkiF+Y57XtB0WfjGuAac5e7P88rk850OlHP7Q2y
          PLATFORM_API_BASE_URL: 'https://qa-platform.nypl.org/api/v0.1/'
          NYPL_OAUTH_URL: https://isso.nypl.org/
          NYPL_OAUTH_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHoweAYJKoZIhvcNAQcGoGswaQIBADBkBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJq7hyaXKKaj5QixqAIBEIA3mLO2In6BNVmyKofS9hV5jcypFtDKyAketioio3lII4ZcSOeIyy5n4iVgGPWvGelVF1p1G2sF/A==
          NYPL_OAUTH_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzkX7gcpNs1o60OAUQCARCAQ8ynMnFDjUV10qoJLRfLnVq/wrPglX65R3YLIEDKBa4W2e7CCQD6zDGCPIltDzGq9q6kjefIyHcjqSKlpKiYqqm/yw0=
          LIB_ANSWERS_EMAIL_SASB: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHkwdwYJKoZIhvcNAQcGoGowaAIBADBjBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDDGdjzWd58Ys7Yw5BQIBEIA2QQ2FJiOkd27QWGR1KfPWpBLgrllDLTIUtodAAry+b/Knqar1XwjO4vF5Z+tIbMeg7EplgUJB
          LIB_ANSWERS_EMAIL_LPA: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHgwdgYJKoZIhvcNAQcGoGkwZwIBADBiBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDH7zdJ58EU+hS4wWXgIBEIA1QpAqum+V8QkVFbZMP5s6FyRZ62FVnHAt8BJEFR9kNB5vwCZGD3/4dPTC9lzX0LNsS7NLeWM=
          LIB_ANSWERS_EMAIL_SC: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHoweAYJKoZIhvcNAQcGoGswaQIBADBkBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDLh2dXusxY9yiPnNdwIBEIA3/sXngKmdmPri2d5jM3vSi+H5XfYyXhmOyVrsbyC3vAv3xmZdKlNKomed+sTr8alcsDJLkJsrKQ==
          APP_ENV: 'development'
          DEVELOPMENT_LIB_ANSWERS_EMAIL:
          LIB_ANSWERS_EMAIL_SC_BCC:
          LIB_ANSWERS_EMAIL_SASB_BCC:
          LIB_ANSWERS_EMAIL_LPA_BCC:
          RC_QA_DOMAIN: 'qa-www.nypl.org'
      Events:
        ApiCreateHoldRequestsPath:
          Type: Api
          Properties:
            Path: "/api/v0.1/on-site-hold-requests"
            Method: POST
        DocsPath:
          Type: Api
          Properties:
            Path: "/docs/on-site-hold-requests"
            Method: GET
